### ISSUE TITLE
constchar* return value throws exception

### ISSUE THREAD

**Issue by karmag** [bagucode/clj-native#1]
Declaring a const char\* return value throws an exception. ("Typed pointer not allowed as return-value" or something to that extent.)

As I understand it this is a security measure to prevent you from blowing yourself up. const char\* however seems like a pretty common type and supporting it would be a nice feature for the end-user.

**Comment by bagucode** [comment]
Fixed.
It's now allowed to use constchar\* and constwchar_t\* as return types.
constchar\* becomes a regular java string but constwchar_t\* becomes a JNA WString.

**Comment by bagucode** [comment]
Closing
