### ISSUE TITLE
Proposal: Support search path

### ISSUE THREAD

**Issue by glyh** [bagucode/clj-native#10]
The current implementation seems only load libraries from some specific path. 

But with these codes, we can search for libraries in arbitrary paths: 
```java
import com.sun.jna.NativeLibrary;
//......
NativeLibrary.addSearchPath("opencv", "C:\\opencv");
OpenCV openCV = (OpenCV)NativeLibrary.loadLibrary("opencv", OpenCV.class);
```

**Comment by glyh** [comment]
Sorry, I found that it's already demonstrated in the example, closing up.

**Comment by bagucode** [comment]
No problem :)
I hope you find this library useful.
I have not worked on it for years but please tell me if there are any problems and maybe I can fix it.

**Comment by glyh** [comment]
I will, thank you for your library!
