### ISSUE TITLE
push 0.9.3-SNAPSHOT to clojars?

### ISSUE THREAD

**Issue by rogerallen** [bagucode/clj-native#4]
Hi there,

It appears Overtone is relying on the latest 0.9.3-SNAPSHOT code now. https://github.com/overtone/overtone/blob/master/project.clj    

Looking on clojars https://clojars.org/repo/clj-native/clj-native/, only 0.9.2 is available.  

Could you push out a new version, please?

Thanks!

--Roger

p.s. thanks for fixing up the FIXME testcases!

**Comment by bagucode** [comment]
Done
