### ISSUE TITLE
Update JNA dependency?

### ISSUE THREAD

**Issue by rogerallen** [bagucode/clj-native#7]
[net.java.dev.jna/jna "3.4.0"] is pretty old (2011) and doesn't appear to be up-to-date for ARM chips.  Any chance we could get an updated version?

I believe this is preventing Overtone from running on ARM.  See https://groups.google.com/forum/#!topic/overtone/53jRQWBy4Rw

**Comment by rogerallen** [comment]
One thing that will need to be fixed is a breaking JNA change from 3.4 -> 3.5.  From [this thread](https://groups.google.com/forum/#!topic/jna-users/ju0CyEmiU_4)

```
> MUST i define getFieldOrder() for all subclass of Structure? 
From now on (jna 3.5.0 forward) you must define getFieldOrder(). 
```

It also points to https://github.com/twall/jna/blob/master/www/GettingStarted.md where there is an example of getFieldOrder()

When running `lein test` on any later library, I hit that exact issue:

```
Exception in thread "main" java.lang.AbstractMethodError: com.sun.jna.Structure.getFieldOrder()Ljava/util/List;, compiling:(clj_native/test/c_lib.clj:45)
```

**Comment by bagucode** [comment]
Upgraded the JNA dependency. You can get version 0.9.4 of clj-native from Clojars.

**Comment by rogerallen** [comment]
Fantastic!  Thank you so much.  I've confirmed this works with Overtone for a simple test.  

p.s. I was kind of freaking myself out trying to understand the asm library.  So happy to not have to do that!  :smiley:
